---
all:
  hosts:
    vm-db-01:
      ansible_host: 192.168.50.42
      ansible_user: student
      ansible_password: "1"
    vm-web-01:
      ansible_host: 192.168.50.43
      ansible_user: student
      ansible_password: "1"
  children:
    db_servers:
      hosts:
        vm-db-01:
    web_servers:
      hosts:
        vm-web-01:
...
