---
plugin: community.vmware.vmware_vm_inventory
strict: false

# Nap tag va cac thuoc tinh tuy chinh cua vCenter
with_tags: true
with_custom_values: true
with_metadata: true

compose:
  ansible_user: "'root'"
  ansible_connection: "'ssh'"

# Tu dong tao cac nhom con de phan loai may ao trong inventory
keyed_groups:
  - key: summary.runtime.powerState
    prefix: power_state
  - key: guest.guestId
    prefix: os_type
...
