---
plugin: vmware.vmware.vmware_vm_inventory
strict: false

# Thong tin ket noi den vCenter de lay danh sach may ao dong
hostname: "vcenter.local.amigo.com"
username: "administrator@vsphere.local"
password: "YOUR_VCENTER_PASSWORD_HERE"
validate_certs: false

# Lay day du sieu du lieu (metadata) cua VM
with_metadata: true

# Phan nhom (grouping) may ao tu dong trong inventory:
# Vi du: Gom nhom may ao theo trang thai nguon (poweredOn, poweredOff)
# va theo he dieu hanh khach (guest OS)
keyed_groups:
  - key: config.name
    prefix: vm_name
  - key: summary.runtime.powerState
    prefix: power_state
  - key: guest.guestId
    prefix: os_type
...
