---
collections:
  - name: vmware.vmware
    version: "2.9.0"
    source: redhat_hub
  - name: vmware.vmware_rest
    source: redhat_hub
  - name: community.vmware
    source: galaxy
    version: "4.8.5"
...
