[masters]
k8s-master ansible_host=10.1.68.140

[workers]
k8s-worker ansible_host=10.1.68.141

[k8s:children]
masters
workers

[k8s:vars]
ansible_user=ducnam
ansible_password="1"
ansible_become=true
ansible_become_method=sudo
ansible_become_pass="1"
ansible_ssh_common_args="-o StrictHostKeyChecking=no"
