---
# defaults file for vmware_provision

# Thong so ha tang ao hoa mac dinh
vm_datacenter: "Amigo"
vm_cluster: "Amigo 2"
vm_resource_pool: "Software-2"
vm_datastore: "san-datastore-01"
vm_folder: "/vm/Production"
vm_network: "VM-Network-VLAN50"

# Thong so phan cung may ao mac dinh
vm_name: "amigo-web-temp"
vm_cpu: 2
vm_ram_mb: 4096
vm_disk_gb: 50
vm_state: "poweredon"
...
