---
# defaults file for vmware_provision

# Thong so ha tang ao hoa mac dinh
vm_datacenter: "Amigo"
vm_cluster: "Amigo 2"
vm_resource_pool: "Software-2"
vm_datastore: "vsanDatastore"
vm_folder: "/vm/Software-2"
vm_network: "192.168.50.0"
vm_dvswitch_name: "" # Điền tên DVS Switch của bạn nếu gặp lỗi quét cạc mạng DVS (ví dụ: "DSwitch")
vm_module_type: "certified"
# Thong so phan cung may ao mac dinh
vm_name: "amigo-web-temp"
vm_cpu: 2
vm_ram_mb: 4096
vm_disk_gb: 50
vm_state: "poweredon"
...
