---
# meta file for vmware_management (dependencies and info)
galaxy_info:
  author: "Nguyen Duc Nam"
  description: "Role tu dong hoa quan ly he thong vCenter"
  company: "Amigo Technologies"
  license: "MIT"
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - 9
  categories:
    - cloud
    - system

dependencies: []
...
