---
- name: "Chung minh import_role khong cho phep dat ten role bang bien dong"
  hosts: localhost
  gather_facts: false
  vars:
    my_dynamic_role: "demo_role"
  tasks:
    - name: "Task truoc khi import"
      ansible.builtin.debug:
        msg: "Task nay se khong bao gio duoc chay vi loi cu phap xay ra ngay tu dau!"

    - name: "Import role dung bien dong (Se bao loi Compile-time)"
      ansible.builtin.import_role:
        name: "{{ my_dynamic_role }}"
...

