---
# ==============================================================================
# BƯỚC 1: KIỂM TRA KẾT NỐI API VCENTER
# Job Template AWX: 01-vCenter-Test-Connection
# Ưu tiên Red Hat Certified vmware.vmware, tự động hỗ trợ community.vmware
# ==============================================================================

- name: "[STEP 1] Kiểm tra kết nối vCenter API"
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - vmware.vmware
    - community.vmware

  tasks:
    - name: "1. Thử nghiệm kết nối vCenter API"
      vmware_about_info:
        validate_certs: false
      register: vcenter_info

    - name: "2. Hiển thị thông tin vCenter kết nối thành công"
      ansible.builtin.debug:
        msg:
          - "=========================================================="
          - "--> Trạng thái: KẾT NỐI VCENTER THÀNH CÔNG!                "
          - "=========================================================="
          - " Thông tin vCenter: {{ vcenter_info.about_info | default(vcenter_info) }}"
...
