---
- name: Kich ban tu dong hoa tao moi may ao tren vSphere vCenter
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: "amigo-web-prod-01"
    vm_cpu: 4
    vm_ram_mb: 8192

  tasks:
    - name: "Thuc thi quy trinh khoi tao may ao"
      block:
        - name: "1. Khoi chay Role vmware_provision de tao VM"
          ansible.builtin.include_role:
            name: vmware_provision

      rescue:
        - name: "2. Xu ly canh bao khi gap loi tao may ao"
          ansible.builtin.fail:
            msg: >
              TIEN TRINH KHOI TAO MAY AO '{{ vm_name }}' BI LOI!
...
